- name: "Install minikube"
  dnf:
    name: https://github.com/kubernetes/minikube/releases/download/v1.30.1/minikube-1.30.1-0.x86_64.rpm
    state: present
    disable_gpg_check: true
  when: ('minikube' not in ansible_facts.packages)
- name: "Reset connection"
  meta: reset_connection

- name: "Minikube"
  block:
    - name: "Start minikube"
      shell: "minikube start --vm-driver=docker --addons=ingress --memory=6g --cpus=2"
    - name: "Add kubectl alias"
      lineinfile:
        path: ~/.bashrc
        line: "alias kubectl='minikube kubectl --'"
  become_user: "{{ user }}"
  when: ('minikube' not in ansible_facts.packages)
